language: python
python: 
  - "3.7"
services:
  - docker
install:
  - pip install -r requirements.base.txt
before_script: pip install docker-compose
script:
  - docker-compose run app sh -c "python manage.py test && flake8"